apiVersion: v1
kind: Service
metadata:
  name: chronograf
  namespace: influx
  labels:
    app: chronograf
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8888
  selector:
    app: chronograf