apiVersion: v1
kind: Service
metadata:
  name: influxdb
  namespace: influx
  labels:
    app: influxdb
spec:
  type: ClusterIP
  ports:
  - name: api
    port: 8086
    targetPort: 8086
  selector:
    app: influxdb