apiVersion: v1
kind: Service
metadata:
  name: kapacitor
  namespace: influx
  labels:
    app: kapacitor
spec:
  type: ClusterIP
  ports:
  - port: 9092
    targetPort: 9092
    name: api
  selector:
    app: kapacitor