apiVersion: v1
kind: Service
metadata:
  name: telegraf
  namespace: influx
spec:
  type: ClusterIP
  ports:
  - port: 8125
    targetPort: 8125
    protocol: UDP
    name: statsd
  selector:
    app: telegraf