apiVersion: v1
kind: ConfigMap
metadata:
  name: telegraf
  namespace: influx
  labels:
    app: telegraf
data:
  telegraf.conf: |+

    [agent]
      collection_jitter = "0s"
      debug = false
      flush_interval = "10s"
      flush_jitter = "0s"
      hostname = "telegraf-polling-service"
      interval = "10s"
      logfile = ""
      metric_batch_size = 1000
      metric_buffer_limit = 10000
      omit_hostname = false
      precision = ""
      quiet = false
      round_interval = true

    [[outputs.influxdb]]
      database = "telegraf"
      urls = [
        "http://influxdb.influx:8086"
      ]
    [[inputs.system]]
    [[inputs.cpu]]
      percpu = false
      totalcpu = true
    [[inputs.influxdb]]
      timeout = "5s"
      urls = [
        "http://influxdb.influx:8086/debug/vars"
      ]
    [[inputs.kapacitor]]
      timeout = "5s"
      urls = [
        "http://kapacitor.influx:9092/debug/vars"
      ]
    [[inputs.statsd]]
      allowed_pending_messages = 10000
      metric_separator = "_"
      percentile_limit = 1000
      percentiles = [
        50,
        95,
        99
      ]
      service_address = ":8125"
    [[inputs.kafka_consumer]]
      topics = ["telegraf"]
      brokers = ["kafka-1.kafka:9092", "kafka-2.kafka:9092", "kafka-3.kafka:9092"]
      consumer_group = "telegraf_metrics_consumers"
      offset = "oldest"
      data_format = "influx"
      max_message_len = 65536
    [[inputs.mongodb]]
      servers = ["mongodb://mongo.mongo:27017"]